[tool.poetry]
name = "pyml"
version = "0.1.0"
description = "Simple project to implement various ML techniques"
authors = ["T. E. Kalayci"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
pip = "^21.0"
# DS Libraries
numpy = "^1.20"
pandas = "^1.2"
scipy = "^1.6"
scikit-learn = "^0.24"
easydict = "^1.9"
plydata = "^0.4.3"
pysistence = "^0.4"
# Visualization
matplotlib = "^3.4"
seaborn = "^0.11"
plotly = "^4.14"
# JupyterLab
jupyter = "^1.0"
jupyterlab = "^3.0"
ipympl = "^0.7"
ipywidgets = "^7.6"
jupyterlab-widgets = "^1.0"
jupyterlab_code_formatter = "^1.4"
black = "^20.8b1"
isort = "^5.8"
jupyterlab-drawio = "^0.8"
lckr-jupyterlab-variableinspector = "^3.0"
jupyterlab-dash = "^0.1.0-alpha.3"
jupyterlab-execute-time = "^2.0"
jupyterlab-system-monitor = "^0.8"
jupyterlab-git = "^0.30.0b1"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5"
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
