[tool.poetry]
name = "pyml"
version = "0.1.0"
description = "Simple project to implement various ML techniques"
authors = ["T. E. Kalayci"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "~3.11"
# DS Libraries
easydict = "^1.9"
numpy = "^1.26"
pandas = "^2.1"
plydata = "^0.4"
pysistence = "^0.4"
requests = "*"
scipy = "^1.11"
scikit-learn = "^1.3"
# Visualization
matplotlib = "^3.4"
seaborn = "^0.11"
plotly = "^5.18"
# JupyterLab
jupyter = "*"
jupyterlab = "^4.0"
ipympl = "*"
ipywidgets = "*"
jupyterlab-widgets = "*"
jupyterlab_code_formatter = "*"
black = "*"
isort = "*"
lckr-jupyterlab-variableinspector = "*"
jupyterlab-dash = "*"
jupyterlab-execute-time = "*"
jupyterlab-git = "*"

[tool.poetry.dev-dependencies]
autopep8 = "^2.0"
pytest = "^7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
